import { PageFrame } from "@/components/shared/page-frame";

export default function StudentAdmitCardsPage() {
  return (
    <PageFrame
      eyebrow="Admit Cards"
      title="View admit cards"
      description="Admit cards will be shown here once generated by the backend document system."
    >
      <div className="glass-card p-5 text-sm text-muted-foreground">Admit card list placeholder.</div>
    </PageFrame>
  );
}
